config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  resources :users, only: [:index, :new, :create]
  resources :groups, only: [:new, :create, :destroy]
  resources :entities, only: [:new, :create, :destroy]

  devise_for :users

  # The root path will be spash screen
  root to: 'splash#index'

  # expenses route
  get 'expenses', to: 'expenses#index', as: :expenses
  
  # Specific expense route
  get 'expenses/:id', to: 'expenses#show', as: :expense

  # Payments under specific expense
  get 'expenses/:id/payments', to: 'payments#index', as: :payments

  # Specific payment path
  get 'expenses/:id/payments/:id', to: 'payments#show', as: :payment

  # new payments path
  get 'new_payments', to: 'payments#new', as: :new_payment

  # Specific expense route
  get 'new_expenses', to: 'expenses#new', as: :new_expense

  resources :expenses do
    resources :payments, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user (not logged in)

    can :read, :all
    can :destroy, Food, user_id: user.id
    can :destroy, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
    can :manage, Recipe, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :expense, class_name: 'Expense', foreign_key: 'transaction_id'

  validates :name, presence: true
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Include Devise modules for authentication and others as needed
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :timeoutable,
         stretches: 13, # Cost of the hashing algorithm (default is 11)
         remember_for: 2.weeks, # Expiration period for the "remember me" feature (default is 2.weeks)
         timeout_in: 30.minutes # Period of inactivity before a user is automatically logged out (default is nil)

  validates :name, presence: true
  has_many :payments, foreign_key: :author_id
  has_many :expenses, foreign_key: :transaction_id
end

app/controllers/api_controller.rb
# app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :json
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    # logic to add
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || expenses_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/expense_categories.rb
class ExpenseCategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @transactions = Expense.order(created_at: :desc)
  end

  def show
    @user = current_user
    @transactions = transaction.includes(:user).find(params[:id])
    @payment = Payment.all
  end

  def new
    # @transactions = current_user.payments.build
    @current_user = current_user
  end

  def create
    @transaction = current_user.transactions.build(transaction_params)
    @transaction.created_at ||= Time.current

    if @transaction.save
      redirect_to user_recipes_path(@transaction.user, @payment), notice: 'transaction created successfully.'
    else
      flash.now[:alert] = @transaction.errors.full_messages.join(', ')
    end
  end

  def update
    @transaction = transaction.find(params[:id])
    if @transaction.update(transaction_params)
      redirect_to user_recipe_path(id: @transaction.id)
    else
      render :edit
    end
  end

  def destroy
    @transaction = transaction.find(params[:id])
    authorize! :destroy, @transaction
    @recipe.destroy
    redirect_to transactions_path, notice: 'transaction was successfully deleted.'
  end

  private

  def transaction_params
    params.require(:recipe).permit(:name, :icon, :created_at)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  ICONS = %w[CHARITY ENTERTAINMENT GROCERY FITNESS RECREATIONAL TRAVEL].freeze
  def index
    @last_expense = Expense.last
    @user = current_user
    @expenses = Expense.order(created_at: :desc)
    @payments = Payment.all
  end

  def show
    @user = current_user
    @expenses = Expense.order(created_at: :desc)
    @expense = Expense.find(params[:id])
  end

  def new
    @expenses = Expense.order(created_at: :desc)
    @current_user = current_user
  end

  def create
    if expense_params[:name].present? && expense_params[:icon].present?
      @expense = Expense.new(expense_params[:expense])
      @expense.user_id = current_user.id
      @expense.created_at = Time.current
      @expense.updated_at = Time.current
      @expense.name = expense_params[:name]
      @expense.icon = expense_params[:icon]

      if @expense.save
        redirect_to expenses_path, notice: 'Transaction created successfully.'
      else
        flash.now[:alert] = @expense.errors.full_messages.join(', ')
        render :new
      end
    else
      @name_error = 'Name is required.' if expense_params[:name].blank?
      @icon_error = 'Icon is required.' if expense_params[:icon].blank?

      flash.now[:alert] = 'Both name and icon are required.'
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @expense = Expense.find(params[:id])
    @payments = Payment.order(created_at: :desc)
  end

  def show
    @user = current_user
    @expenses = Expense.order(created_at: :desc)
    @expense = Expense.find(params[:id])
    @payments = @expense.payments
  end

  def new
    @expense = Expense.find(params[:expense_id])
    @payment = Payment.new
  end

  def create
    @expense = Expense.find(params[:expense_id])
    @payment = Payment.new(payment_params)
    @payment.transaction_id = @expense.id
    @payment.created_at = Time.now
    @payment.updated_at = Time.now
    @payment.author_id = current_user.id

    if @payment.save
      redirect_to payments_path(id: @expense.id), notice: 'Payment created successfully.'
    else
      flash.now[:alert] = @payment.errors.full_messages.join(', ')
      puts @payment.errors.full_messages.join(', ')

      render :new
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, :payment_transaction_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ActionController::Base
  before_action :redirect_authenticated_user, if: :user_signed_in?
  def after_sign_out_path_for(_resource_or_scope)
    splash_path
  end

  def redirect_authenticated_user
    redirect_to expenses_path
  end

  def index
    @user = current_user
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # POST /resource/sign_in
  def create
    puts "Parameters received: #{params.inspect}"
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.includes(:payments).all
  end

  def show
    @user = User.includes(:payments).find(params[:id])
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense Transactions app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="flex-column-centered expenses ">
    <div class="transaction-list hidden-scroll">
      <% @expenses.each do |expense| %>
        <%= link_to payments_path(id: expense.id), class: "transaction-name some-class" do %>
        <div class="transaction-row flex-centered">
          <div class="flex-spaced">
            <div class="flex-spaced">
            <p><%= image_tag("#{expense.icon.upcase}.png", alt: "Back") %></p>
              <div class="transaction-name"><%= expense.name %></div>
            </div>
          </div>
          <div class="transaction-created-at">
            <% sum = 0 %>
            <% count = 0 %>
            <% @payments.select { |payment| payment.transaction_id == expense.id }.each do |payment| %>
                <% sum += payment.amount %>
                <% count += 1 %>
            <% end %>
            <%= count %> Items,
            Total $<%= sum %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="box w-100 fit-content">
      <%= link_to 'Add Expense Category', new_expense_path, class: 'inner-border no-decoration new-payment-btn ' %>
  </div>
  </div>
  </body>

</html>

app/views/expenses/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense Transactions app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= link_to expenses_path, class: 'bk' do %>
    <%= image_tag("back-arrow.png", alt: "Back") %>
  <% end %>
  
    <%= form_with(model: @expense, url: expenses_path) do |form| %>
      <div class="flex-centered bg-primary ctr-primary  flex-column-centered">
        <div class="flex-column rad-10 w-30">
          <div class="form-field flex-column-centered mt-m10 select">
            <%= form.fields_for :expense do |expense_form| %>
              <%= expense_form.text_field :name, class: "add-food-filds #{'field-with-error' if @name_error.present?}", placeholder: "Enter expense name" %>
              <% if @name_error.present? %>
                <p class="error-message"><%= @name_error %></p>
              <% end %>
              
              <%= expense_form.select :icon, ExpensesController::ICONS, prompt: "Choose an icon for your expense category.", class: "select-field #{'field-with-error' if @icon_error.present?}", id: "select-field" %>
              <% if @icon_error.present? %>
                <p class="error-message"><%= @icon_error %></p>
              <% end %>
            <% end %>
            <div class="flex-spaced">
              <div class="fit ">
                <p><%= image_tag("CHARITY.png", alt: "Back") %></p>
                Charity
              </div>
              <div class="fit ">
                <p><%= image_tag("ENTERTAINMENT.png", alt: "Back") %></p>
                Entertainment
              </div>
              <div class="fit ">
                <p><%= image_tag("GROCERY.png", alt: "Back") %></p>
                Grocery
              </div>
          
            </div>
        
            <div class="box">
              <button type="submit" class="transparent inner-border no-decoration new-payment-btn pointer">Add Expense</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expense Tracking app</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <div class="header-label">
    <div class="flex-spaced p-1  mt-50p">
      <div class="mobile-menu-icon">
        <% if (current_user) %>
        <button id="sidebarToggle">
          <%= image_tag "menu.png", alt: "Menu icon" %>
        </button>
        <% end %>
      </div>
      <% if current_page?(new_user_registration_path) %>
        <div class="title">Register</div>
      <% elsif current_page?(user_session_path) %>
        <div class="title">Login</div>
      <% elsif current_page?(expenses_path) %>
        <div class="title">Expense Categories</div>
      <% elsif current_page?(new_user_password_path) %>
        <div class="title">Reset Password</div>
      <% elsif current_page?(payments_path(1)) %>
        <div class="title">Payment Details</div>
      <% elsif current_page?(new_payment_path) %>
        <div class="title">Add New Payment</div>
      <% elsif current_page?(new_expense_path) %>
        <div class="title">New Expense</div>
      <% else %>
        <!-- Default content if none of the conditions match -->
      <% end %>
      <div>
        <%= image_tag "search.png", alt: "Search icon" %>
      </div>
    </div>
  </div>

  <!-- Sidebar menu -->
  <% if current_user %>
  <div id="sidebar" class="sidebar">
  <div class="current_user flex-column-centered mt-3 mb-3">
    <%= current_user.name %>
  </div>
  <ul class="list-group">
    <li class="list-group-item <%= 'active' if current_page?(expenses_path) %>">
      <%= link_to expenses_path, class: 'list-group-items' do %>
        <div class="list-group-item-content">Expenses</div>
      <% end %>
    </li>
  
    <li class="list-group-item <%= 'active' if current_page?(new_payment_path) %>">
    <%= link_to new_expense_path, class: 'list-group-items' do %>
      <div class="list-group-item-content">New Expense</div>
    <% end %>
    </li>
    <% if Expense.last %>
    <li class="list-group-item <%= 'active' if current_page?(new_payment_path) %>">
      <%= link_to new_payment_path(expense_id: Expense.last.id), class: 'list-group-items' do %>
        <div class="list-group-item-content">New Payments</div>
      <% end %>
    </li>
  <% end %>
    <li class="list-group-item <%= 'active' if current_page?(payments_path(1)) %>">
      <%= link_to payments_path(1), class: 'list-group-items' do %>
        <div class="list-group-item-content">Payments</div>
      <% end %>
    </li>
  </ul>
</div>
<% end %>

  <main>
    <%= yield %>
  </main>

  <footer>
    <!-- Footer content here -->
  </footer>

</body>
</html>

app/views/payments/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="hidden-scroll">
    <%= link_to expenses_path, class: 'bk' do %>
      <%= image_tag("back-arrow.png", alt: "Back") %>
    <% end %>
  <% sum = 0 %>
  <div class="payments flex-column-centered hidden-scroll ">
  <div class="flex-column-centered payment-details hidden-scroll relative">
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <% @payments.each do |payment| %>
    <% if (payment.transaction_id == @expense.id) %>
    <% sum += payment.amount %>
        <div class="detail">
            <p class="payment-name flex-column-start">
              <%= payment.name %>
            </p>
          <div class="flex-column-start gap-10p relative">
            <p class="payment-date  flex-start">
              <p><%= payment.created_at.strftime('%e %B %Y ') %></p>
              <p><%= payment.created_at.strftime('at %l:%M %p') %></p>
            </p>
            <p class="payment-amount  flex-start">
                 $<%= payment.amount %>
            </p>
          </div>
        </div>
    <% end %>
  <% end %>
  <div class="total absolute">
    Total $<%= sum %>
  </div>
  </div>  
  </body>
  <div class="flex-column-centered fixed bottom-centered  ">
  <div class="   box ">
  <%= link_to 'Add Payment', new_payment_path(expense_id: @expense.id), class: 'inner-border no-decoration new-payment-btn' %>
        </div>
  </div>
  </div>
</html>

app/views/payments/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    </head>
    
    <body>
    <%= link_to payments_path(id: @expense.id), class: 'bk' do %>
      <%= image_tag("back-arrow.png", alt: "Back") %>
    <% end %>
    
    <%= form_with(model: @payment, url: expense_payments_path(@expense)) do |form| %>
    <div class="flex-centered bg-primary ctr-primary ">
    <div class=" flex-column rad-10 w-30">
      <div class="form-field flex-column-centered mt-m10">
        <div class="field flex-start">
          <%= form.text_field :name, class: "add-food-filds", placeholder: "Enter name" %>
          </div>
          <div class="name-field flex-start">
          <%= form.text_field :amount, class: "add-food-filds", placeholder: "Enter amount" %>
          </div>
        <div class="box">
          <div class="inner-border">
            <button type="submit">Submit</button>
          </div>
        </div>
      </div>
      </div>
      </div>
      <% end %>
  </body>
</html>





 

app/views/payments/view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Payments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    </head>
    
    <body>
        <div>Show Payments</div>
  </body>
</html>

app/views/splash/index.html.erb
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; background-color: #f7f7f7;">
  <h1 style="font-size: 2rem; margin-bottom: 20%; color: #424a53; font-size: 50px; font-family: 'Dancing Script', cursive; ">Expense Tracking App</h1>
  <div style="display: flex;  flex-direction: column; align-items: center; gap: 1.5rem; width: 100%; position: absolute; bottom: 4%;">
    <%= link_to "Login", new_user_session_path, style: "padding: 1rem 2rem;  font-size: 1.4rem; background-color: #007bff; color: white; font-family: 'Montserrat', sans-serif; border: none; border-radius: 0.25rem; text-align: center; text-decoration: none; cursor: pointer; transition: background-color 0.3s ease-in-out; width: 20%;", class: "btn-hover" %>
    <%= link_to "Register", new_user_registration_path, style: "padding: 1rem 2rem;  font-size: 1.4rem; color: #424a53; font-family: 'Montserrat', sans-serif; border: none; border-radius: 0.25rem; text-align: center; text-decoration: none; cursor: pointer; transition: background-color 0.3s ease-in-out; width: 25%; margin-left: 10px;", class: "btn-hover" %>
  </div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Blog App</title>
</head>
<body>
users index
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Profile</title>
</head>
<body>
  <div class="user-container ">
    
  </div> 
</body>
</html>